import type { DeepSkyObject, PlanningProfile } from "../types";
import { buildPlanningProfile } from "./objectProfiles";

interface MessierCatalogSeed extends Omit<DeepSkyObject, "planningProfile"> {
  profileOverrides?: Partial<PlanningProfile>;
}

const messierCatalogSeeds: MessierCatalogSeed[] = [
  {
    "id": "M1",
    "messierNumber": 1,
    "primaryName": "Crab Nebula",
    "germanName": "Krebsnebel",
    "aliases": [
      "M1",
      "M 1",
      "1",
      "NGC 1952",
      "Crab Nebula"
    ],
    "raHours": 5.575,
    "raDeg": 83.625,
    "decDeg": 22.016667,
    "constellation": "Taurus",
    "objectType": "supernova_remnant",
    "objectSubType": "Sn",
    "visualMagnitude": 8.4,
    "apparentSizeArcMin": 6,
    "majorAxisArcMin": 6,
    "minorAxisArcMin": 4,
    "distanceLy": "6300",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M2",
    "messierNumber": 2,
    "primaryName": "Messier 2 globular cluster",
    "aliases": [
      "M2",
      "M 2",
      "2",
      "NGC 7089"
    ],
    "raHours": 21.558333,
    "raDeg": 323.374995,
    "decDeg": -0.816667,
    "constellation": "Aquarius",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 6.5,
    "apparentSizeArcMin": 12.9,
    "majorAxisArcMin": 12.9,
    "minorAxisArcMin": 12.9,
    "distanceLy": "37900",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M3",
    "messierNumber": 3,
    "primaryName": "Messier 3 globular cluster",
    "aliases": [
      "M3",
      "M 3",
      "3",
      "NGC 5272"
    ],
    "raHours": 13.703333,
    "raDeg": 205.549995,
    "decDeg": 28.383333,
    "constellation": "Canes Venatici",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 6.2,
    "apparentSizeArcMin": 16.2,
    "majorAxisArcMin": 16.2,
    "minorAxisArcMin": 16.2,
    "distanceLy": "33900",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M4",
    "messierNumber": 4,
    "primaryName": "Messier 4 globular cluster",
    "aliases": [
      "M4",
      "M 4",
      "4",
      "NGC 6121"
    ],
    "raHours": 16.393333,
    "raDeg": 245.899995,
    "decDeg": -26.533333,
    "constellation": "Scorpius",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 5.6,
    "apparentSizeArcMin": 26.3,
    "majorAxisArcMin": 26.3,
    "minorAxisArcMin": 26.3,
    "distanceLy": "7200",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M5",
    "messierNumber": 5,
    "primaryName": "Messier 5 globular cluster",
    "aliases": [
      "M5",
      "M 5",
      "5",
      "NGC 5904"
    ],
    "raHours": 15.31,
    "raDeg": 229.65,
    "decDeg": 2.083333,
    "constellation": "Serpens",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 5.6,
    "apparentSizeArcMin": 17.4,
    "majorAxisArcMin": 17.4,
    "minorAxisArcMin": 17.4,
    "distanceLy": "24500",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M6",
    "messierNumber": 6,
    "primaryName": "Butterfly Cluster",
    "aliases": [
      "M6",
      "M 6",
      "6",
      "NGC 6405",
      "Butterfly Cluster"
    ],
    "raHours": 17.668333,
    "raDeg": 265.024995,
    "decDeg": -32.216667,
    "constellation": "Scorpius",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 4.2,
    "apparentSizeArcMin": 25,
    "majorAxisArcMin": 25,
    "minorAxisArcMin": 25,
    "distanceLy": "1600",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M7",
    "messierNumber": 7,
    "primaryName": "Ptolemy's Cluster",
    "aliases": [
      "M7",
      "M 7",
      "7",
      "NGC 6475",
      "Ptolemy's Cluster"
    ],
    "raHours": 17.898333,
    "raDeg": 268.474995,
    "decDeg": -34.816667,
    "constellation": "Scorpius",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 3.3,
    "apparentSizeArcMin": 80,
    "majorAxisArcMin": 80,
    "minorAxisArcMin": 80,
    "distanceLy": "800",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M8",
    "messierNumber": 8,
    "primaryName": "Lagoon Nebula",
    "germanName": "Lagunenebel",
    "aliases": [
      "M8",
      "M 8",
      "8",
      "NGC 6523",
      "Lagoon Nebula"
    ],
    "raHours": 18.063333,
    "raDeg": 270.949995,
    "decDeg": -24.383333,
    "constellation": "Sagittarius",
    "objectType": "nebula_cluster_combo",
    "objectSubType": "Di",
    "visualMagnitude": 6,
    "apparentSizeArcMin": 90,
    "majorAxisArcMin": 90,
    "minorAxisArcMin": 40,
    "distanceLy": "5200",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M9",
    "messierNumber": 9,
    "primaryName": "Messier 9 globular cluster",
    "aliases": [
      "M9",
      "M 9",
      "9",
      "NGC 6333"
    ],
    "raHours": 17.32,
    "raDeg": 259.8,
    "decDeg": -18.516667,
    "constellation": "Ophiuchus",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 7.7,
    "apparentSizeArcMin": 9.3,
    "majorAxisArcMin": 9.3,
    "minorAxisArcMin": 9.3,
    "distanceLy": "26700",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M10",
    "messierNumber": 10,
    "primaryName": "Messier 10 globular cluster",
    "aliases": [
      "M10",
      "M 10",
      "10",
      "NGC 6254"
    ],
    "raHours": 16.951667,
    "raDeg": 254.275005,
    "decDeg": -4.1,
    "constellation": "Ophiuchus",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 6.6,
    "apparentSizeArcMin": 15.1,
    "majorAxisArcMin": 15.1,
    "minorAxisArcMin": 15.1,
    "distanceLy": "14400",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M11",
    "messierNumber": 11,
    "primaryName": "Wild Duck Cluster",
    "aliases": [
      "M11",
      "M 11",
      "11",
      "NGC 6705",
      "Wild Duck Cluster"
    ],
    "raHours": 18.851667,
    "raDeg": 282.775005,
    "decDeg": -6.266667,
    "constellation": "Scutum",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 6.3,
    "apparentSizeArcMin": 14,
    "majorAxisArcMin": 14,
    "minorAxisArcMin": 14,
    "distanceLy": "6000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M12",
    "messierNumber": 12,
    "primaryName": "Messier 12 globular cluster",
    "aliases": [
      "M12",
      "M 12",
      "12",
      "NGC 6218"
    ],
    "raHours": 16.786667,
    "raDeg": 251.800005,
    "decDeg": -1.95,
    "constellation": "Ophiuchus",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 6.7,
    "apparentSizeArcMin": 14.5,
    "majorAxisArcMin": 14.5,
    "minorAxisArcMin": 14.5,
    "distanceLy": "16000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M13",
    "messierNumber": 13,
    "primaryName": "Hercules Globular Cluster",
    "germanName": "Herkuleshaufen",
    "aliases": [
      "M13",
      "M 13",
      "13",
      "NGC 6205",
      "Great Hercules Globular",
      "Hercules Globular Cluster",
      "Great Hercules Cluster"
    ],
    "raHours": 16.695,
    "raDeg": 250.425,
    "decDeg": 36.466667,
    "constellation": "Hercules",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 5.8,
    "apparentSizeArcMin": 16.6,
    "majorAxisArcMin": 16.6,
    "minorAxisArcMin": 16.6,
    "distanceLy": "25100",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92,
    "profileOverrides": {
      "moonSensitivity": 0.2,
      "twilightSensitivity": 0.32,
      "altitudeSensitivity": 0.66,
      "gradientSensitivity": 0.18,
      "faintDetailSensitivity": 0.2,
      "surfaceBrightnessClass": "high",
      "broadbandDifficulty": "easy",
      "minUsableAltitudeDeg": 24,
      "minMainAltitudeDeg": 30,
      "idealAltitudeDeg": 48,
      "maxRecommendedMoonIlluminationMain": 80,
      "maxRecommendedMoonIlluminationExtra": 92,
      "minRecommendedMoonDistanceDeg": 30,
      "coreSaturationRisk": "medium",
      "framingDifficulty": "easy",
      "notes": [
        "Bright globular cluster; still useful with moderate moonlight if altitude is good."
      ]
    }
  },
  {
    "id": "M14",
    "messierNumber": 14,
    "primaryName": "Messier 14 globular cluster",
    "aliases": [
      "M14",
      "M 14",
      "14",
      "NGC 6402"
    ],
    "raHours": 17.626667,
    "raDeg": 264.400005,
    "decDeg": -3.25,
    "constellation": "Ophiuchus",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 7.6,
    "apparentSizeArcMin": 11.7,
    "majorAxisArcMin": 11.7,
    "minorAxisArcMin": 11.7,
    "distanceLy": "29000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M15",
    "messierNumber": 15,
    "primaryName": "Great Pegasus Globular",
    "aliases": [
      "M15",
      "M 15",
      "15",
      "NGC 7078",
      "Great Pegasus Globular"
    ],
    "raHours": 21.5,
    "raDeg": 322.5,
    "decDeg": 12.166667,
    "constellation": "Pegasus",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 6.2,
    "apparentSizeArcMin": 12.3,
    "majorAxisArcMin": 12.3,
    "minorAxisArcMin": 12.3,
    "distanceLy": "33600",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M16",
    "messierNumber": 16,
    "primaryName": "Eagle Nebula",
    "germanName": "Adlernebel",
    "aliases": [
      "M16",
      "M 16",
      "16",
      "NGC 6611",
      "Eagle Nebula"
    ],
    "raHours": 18.313333,
    "raDeg": 274.699995,
    "decDeg": -13.783333,
    "constellation": "Serpens",
    "objectType": "nebula_cluster_combo",
    "objectSubType": "Oc",
    "visualMagnitude": 6.4,
    "apparentSizeArcMin": 7,
    "majorAxisArcMin": 7,
    "minorAxisArcMin": 7,
    "distanceLy": "7000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M17",
    "messierNumber": 17,
    "primaryName": "Omega Nebula",
    "germanName": "Omeganebel",
    "aliases": [
      "M17",
      "M 17",
      "17",
      "NGC 6618",
      "Omega Nebula"
    ],
    "raHours": 18.346667,
    "raDeg": 275.200005,
    "decDeg": -16.183333,
    "constellation": "Sagittarius",
    "objectType": "emission_nebula",
    "objectSubType": "Di",
    "visualMagnitude": 7,
    "apparentSizeArcMin": 11,
    "majorAxisArcMin": 11,
    "minorAxisArcMin": 11,
    "distanceLy": "5000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M18",
    "messierNumber": 18,
    "primaryName": "Messier 18 open cluster",
    "aliases": [
      "M18",
      "M 18",
      "18",
      "NGC 6613"
    ],
    "raHours": 18.331667,
    "raDeg": 274.975005,
    "decDeg": -17.133333,
    "constellation": "Sagittarius",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 7.5,
    "apparentSizeArcMin": 9,
    "majorAxisArcMin": 9,
    "minorAxisArcMin": 9,
    "distanceLy": "4900",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M19",
    "messierNumber": 19,
    "primaryName": "Messier 19 globular cluster",
    "aliases": [
      "M19",
      "M 19",
      "19",
      "NGC 6273"
    ],
    "raHours": 17.043333,
    "raDeg": 255.649995,
    "decDeg": -26.266667,
    "constellation": "Ophiuchus",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 6.8,
    "apparentSizeArcMin": 13.5,
    "majorAxisArcMin": 13.5,
    "minorAxisArcMin": 13.5,
    "distanceLy": "28400",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M20",
    "messierNumber": 20,
    "primaryName": "Trifid Nebula",
    "germanName": "Trifidnebel",
    "aliases": [
      "M20",
      "M 20",
      "20",
      "NGC 6514",
      "Trifid Nebula"
    ],
    "raHours": 18.043333,
    "raDeg": 270.649995,
    "decDeg": -23.033333,
    "constellation": "Sagittarius",
    "objectType": "nebula_cluster_combo",
    "objectSubType": "Di",
    "visualMagnitude": 9,
    "apparentSizeArcMin": 28,
    "majorAxisArcMin": 28,
    "minorAxisArcMin": 28,
    "distanceLy": "5200",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M21",
    "messierNumber": 21,
    "primaryName": "Messier 21 open cluster",
    "aliases": [
      "M21",
      "M 21",
      "21",
      "NGC 6531"
    ],
    "raHours": 18.076667,
    "raDeg": 271.150005,
    "decDeg": -22.5,
    "constellation": "Sagittarius",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 6.5,
    "apparentSizeArcMin": 13,
    "majorAxisArcMin": 13,
    "minorAxisArcMin": 13,
    "distanceLy": "4250",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M22",
    "messierNumber": 22,
    "primaryName": "Sagittarius Cluster",
    "aliases": [
      "M22",
      "M 22",
      "22",
      "NGC 6656",
      "Sagittarius Cluster"
    ],
    "raHours": 18.606667,
    "raDeg": 279.100005,
    "decDeg": -23.9,
    "constellation": "Sagittarius",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 5.1,
    "apparentSizeArcMin": 24,
    "majorAxisArcMin": 24,
    "minorAxisArcMin": 24,
    "distanceLy": "10400",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M23",
    "messierNumber": 23,
    "primaryName": "Messier 23 open cluster",
    "aliases": [
      "M23",
      "M 23",
      "23",
      "NGC 6494"
    ],
    "raHours": 17.946667,
    "raDeg": 269.200005,
    "decDeg": -19.016667,
    "constellation": "Sagittarius",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 6.9,
    "apparentSizeArcMin": 27,
    "majorAxisArcMin": 27,
    "minorAxisArcMin": 27,
    "distanceLy": "2150",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M24",
    "messierNumber": 24,
    "primaryName": "Sagittarius Star Cloud",
    "aliases": [
      "M24",
      "M 24",
      "24",
      "Sagittarius Star Cloud"
    ],
    "raHours": 18.281667,
    "raDeg": 274.225005,
    "decDeg": -18.5,
    "constellation": "Sagittarius",
    "objectType": "nebula_cluster_combo",
    "objectSubType": "MW",
    "visualMagnitude": 4.6,
    "apparentSizeArcMin": 90,
    "majorAxisArcMin": 90,
    "minorAxisArcMin": 90,
    "distanceLy": "10000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M25",
    "messierNumber": 25,
    "primaryName": "Messier 25 open cluster",
    "aliases": [
      "M25",
      "M 25",
      "25",
      "IC 4725"
    ],
    "raHours": 18.526667,
    "raDeg": 277.900005,
    "decDeg": -19.25,
    "constellation": "Sagittarius",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 6.5,
    "apparentSizeArcMin": 40,
    "majorAxisArcMin": 40,
    "minorAxisArcMin": 40,
    "distanceLy": "2000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M26",
    "messierNumber": 26,
    "primaryName": "Messier 26 open cluster",
    "aliases": [
      "M26",
      "M 26",
      "26",
      "NGC 6694"
    ],
    "raHours": 18.753333,
    "raDeg": 281.299995,
    "decDeg": -9.4,
    "constellation": "Scutum",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 8,
    "apparentSizeArcMin": 15,
    "majorAxisArcMin": 15,
    "minorAxisArcMin": 15,
    "distanceLy": "5000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M27",
    "messierNumber": 27,
    "primaryName": "Dumbbell Nebula",
    "germanName": "Hantelnebel",
    "aliases": [
      "M27",
      "M 27",
      "27",
      "NGC 6853",
      "Dumbbell Nebula"
    ],
    "raHours": 19.993333,
    "raDeg": 299.899995,
    "decDeg": 22.716667,
    "constellation": "Vulpecula",
    "objectType": "planetary_nebula",
    "objectSubType": "Pl",
    "visualMagnitude": 7.4,
    "apparentSizeArcMin": 8,
    "majorAxisArcMin": 8,
    "minorAxisArcMin": 5.7,
    "distanceLy": "1250",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92,
    "profileOverrides": {
      "moonSensitivity": 0.38,
      "twilightSensitivity": 0.42,
      "altitudeSensitivity": 0.7,
      "gradientSensitivity": 0.36,
      "faintDetailSensitivity": 0.4,
      "maxRecommendedMoonIlluminationMain": 68,
      "maxRecommendedMoonIlluminationExtra": 84,
      "notes": [
        "Bright planetary nebula; altitude and sharpness often matter more than absolute darkness."
      ]
    }
  },
  {
    "id": "M28",
    "messierNumber": 28,
    "primaryName": "Messier 28 globular cluster",
    "aliases": [
      "M28",
      "M 28",
      "28",
      "NGC 6626"
    ],
    "raHours": 18.408333,
    "raDeg": 276.124995,
    "decDeg": -24.866667,
    "constellation": "Sagittarius",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 6.8,
    "apparentSizeArcMin": 11.2,
    "majorAxisArcMin": 11.2,
    "minorAxisArcMin": 11.2,
    "distanceLy": "18600",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M29",
    "messierNumber": 29,
    "primaryName": "Messier 29 open cluster",
    "aliases": [
      "M29",
      "M 29",
      "29",
      "NGC 6913"
    ],
    "raHours": 20.398333,
    "raDeg": 305.974995,
    "decDeg": 38.533333,
    "constellation": "Cygnus",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 7.1,
    "apparentSizeArcMin": 7,
    "majorAxisArcMin": 7,
    "minorAxisArcMin": 7,
    "distanceLy": "4000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M30",
    "messierNumber": 30,
    "primaryName": "Messier 30 globular cluster",
    "aliases": [
      "M30",
      "M 30",
      "30",
      "NGC 7099"
    ],
    "raHours": 21.673333,
    "raDeg": 325.099995,
    "decDeg": -23.183333,
    "constellation": "Capricornus",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 7.2,
    "apparentSizeArcMin": 11,
    "majorAxisArcMin": 11,
    "minorAxisArcMin": 11,
    "distanceLy": "26100",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M31",
    "messierNumber": 31,
    "primaryName": "Andromeda Galaxy",
    "germanName": "Andromedagalaxie",
    "aliases": [
      "M31",
      "M 31",
      "31",
      "NGC 224",
      "Andromeda Galaxy",
      "Andromeda"
    ],
    "raHours": 0.696667,
    "raDeg": 10.450005,
    "decDeg": 41.266667,
    "constellation": "Andromeda",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 3.4,
    "apparentSizeArcMin": 178,
    "majorAxisArcMin": 178,
    "minorAxisArcMin": 63,
    "distanceLy": "3 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92,
    "profileOverrides": {
      "moonSensitivity": 0.68,
      "twilightSensitivity": 0.72,
      "altitudeSensitivity": 0.76,
      "gradientSensitivity": 0.82,
      "faintDetailSensitivity": 0.88,
      "surfaceBrightnessClass": "low",
      "broadbandDifficulty": "moderate",
      "minUsableAltitudeDeg": 26,
      "minMainAltitudeDeg": 36,
      "idealAltitudeDeg": 58,
      "maxRecommendedMoonIlluminationMain": 40,
      "maxRecommendedMoonIlluminationExtra": 60,
      "minRecommendedMoonDistanceDeg": 65,
      "coreSaturationRisk": "high",
      "framingDifficulty": "hard",
      "notes": [
        "Very large and bright core; weak outer halo benefits strongly from dark sky.",
        "Watch framing and core saturation."
      ]
    }
  },
  {
    "id": "M32",
    "messierNumber": 32,
    "primaryName": "Messier 32 elliptical galaxy",
    "aliases": [
      "M32",
      "M 32",
      "32",
      "NGC 221"
    ],
    "raHours": 0.713333,
    "raDeg": 10.699995,
    "decDeg": 40.866667,
    "constellation": "Andromeda",
    "objectType": "galaxy_elliptical",
    "objectSubType": "El",
    "visualMagnitude": 8.1,
    "apparentSizeArcMin": 8,
    "majorAxisArcMin": 8,
    "minorAxisArcMin": 6,
    "distanceLy": "3 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M33",
    "messierNumber": 33,
    "primaryName": "Triangulum Galaxy",
    "germanName": "Dreiecksgalaxie",
    "aliases": [
      "M33",
      "M 33",
      "33",
      "NGC 598",
      "Triangulum Galaxy"
    ],
    "raHours": 1.565,
    "raDeg": 23.475,
    "decDeg": 30.65,
    "constellation": "Triangulum",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 5.7,
    "apparentSizeArcMin": 73,
    "majorAxisArcMin": 73,
    "minorAxisArcMin": 45,
    "distanceLy": "3 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92,
    "profileOverrides": {
      "moonSensitivity": 0.94,
      "twilightSensitivity": 0.93,
      "altitudeSensitivity": 0.86,
      "gradientSensitivity": 0.94,
      "faintDetailSensitivity": 0.96,
      "surfaceBrightnessClass": "very_low",
      "broadbandDifficulty": "extreme",
      "minUsableAltitudeDeg": 32,
      "minMainAltitudeDeg": 45,
      "idealAltitudeDeg": 62,
      "maxRecommendedMoonIlluminationMain": 15,
      "maxRecommendedMoonIlluminationExtra": 30,
      "minRecommendedMoonDistanceDeg": 95,
      "notes": [
        "Large low-surface-brightness galaxy; needs dark moon-free sky."
      ]
    }
  },
  {
    "id": "M34",
    "messierNumber": 34,
    "primaryName": "Messier 34 open cluster",
    "aliases": [
      "M34",
      "M 34",
      "34",
      "NGC 1039"
    ],
    "raHours": 2.7,
    "raDeg": 40.5,
    "decDeg": 42.783333,
    "constellation": "Perseus",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 5.5,
    "apparentSizeArcMin": 35,
    "majorAxisArcMin": 35,
    "minorAxisArcMin": 35,
    "distanceLy": "1400",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M35",
    "messierNumber": 35,
    "primaryName": "Messier 35 open cluster",
    "aliases": [
      "M35",
      "M 35",
      "35",
      "NGC 2168"
    ],
    "raHours": 6.148333,
    "raDeg": 92.224995,
    "decDeg": 24.333333,
    "constellation": "Gemini",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 5.3,
    "apparentSizeArcMin": 28,
    "majorAxisArcMin": 28,
    "minorAxisArcMin": 28,
    "distanceLy": "2800",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M36",
    "messierNumber": 36,
    "primaryName": "Messier 36 open cluster",
    "aliases": [
      "M36",
      "M 36",
      "36",
      "NGC 1960"
    ],
    "raHours": 5.601667,
    "raDeg": 84.025005,
    "decDeg": 34.133333,
    "constellation": "Auriga",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 6.3,
    "apparentSizeArcMin": 12,
    "majorAxisArcMin": 12,
    "minorAxisArcMin": 12,
    "distanceLy": "4100",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M37",
    "messierNumber": 37,
    "primaryName": "Messier 37 open cluster",
    "aliases": [
      "M37",
      "M 37",
      "37",
      "NGC 2099"
    ],
    "raHours": 5.873333,
    "raDeg": 88.099995,
    "decDeg": 32.55,
    "constellation": "Auriga",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 6.2,
    "apparentSizeArcMin": 24,
    "majorAxisArcMin": 24,
    "minorAxisArcMin": 24,
    "distanceLy": "4400",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M38",
    "messierNumber": 38,
    "primaryName": "Messier 38 open cluster",
    "aliases": [
      "M38",
      "M 38",
      "38",
      "NGC 1912"
    ],
    "raHours": 5.478333,
    "raDeg": 82.174995,
    "decDeg": 35.833333,
    "constellation": "Auriga",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 7.4,
    "apparentSizeArcMin": 21,
    "majorAxisArcMin": 21,
    "minorAxisArcMin": 21,
    "distanceLy": "4200",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M39",
    "messierNumber": 39,
    "primaryName": "Messier 39 open cluster",
    "aliases": [
      "M39",
      "M 39",
      "39",
      "NGC 7092"
    ],
    "raHours": 21.536667,
    "raDeg": 323.050005,
    "decDeg": 48.433333,
    "constellation": "Cygnus",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 4.6,
    "apparentSizeArcMin": 32,
    "majorAxisArcMin": 32,
    "minorAxisArcMin": 32,
    "distanceLy": "825",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M40",
    "messierNumber": 40,
    "primaryName": "Winnecke 4",
    "aliases": [
      "M40",
      "M 40",
      "40",
      "Winnecke 4"
    ],
    "raHours": 12.373333,
    "raDeg": 185.599995,
    "decDeg": 58.083333,
    "constellation": "Ursa Major",
    "objectType": "asterism",
    "objectSubType": "Ds",
    "visualMagnitude": 8.4,
    "apparentSizeArcMin": 0.8,
    "majorAxisArcMin": 0.8,
    "minorAxisArcMin": 0.8,
    "distanceLy": "510",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M41",
    "messierNumber": 41,
    "primaryName": "Messier 41 open cluster",
    "aliases": [
      "M41",
      "M 41",
      "41",
      "NGC 2287"
    ],
    "raHours": 6.783333,
    "raDeg": 101.749995,
    "decDeg": -20.733333,
    "constellation": "Canis Major",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 4.6,
    "apparentSizeArcMin": 38,
    "majorAxisArcMin": 38,
    "minorAxisArcMin": 38,
    "distanceLy": "2300",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M42",
    "messierNumber": 42,
    "primaryName": "Orion Nebula",
    "germanName": "Orionnebel",
    "aliases": [
      "M42",
      "M 42",
      "42",
      "NGC 1976",
      "Great Nebula in Orion",
      "Orion Nebula",
      "Great Orion Nebula"
    ],
    "raHours": 5.59,
    "raDeg": 83.85,
    "decDeg": -5.45,
    "constellation": "Orion",
    "objectType": "emission_nebula",
    "objectSubType": "Di",
    "visualMagnitude": 4,
    "apparentSizeArcMin": 85,
    "majorAxisArcMin": 85,
    "minorAxisArcMin": 60,
    "distanceLy": "1600",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92,
    "profileOverrides": {
      "moonSensitivity": 0.48,
      "twilightSensitivity": 0.48,
      "altitudeSensitivity": 0.66,
      "gradientSensitivity": 0.55,
      "faintDetailSensitivity": 0.66,
      "surfaceBrightnessClass": "high",
      "broadbandDifficulty": "moderate",
      "minUsableAltitudeDeg": 25,
      "minMainAltitudeDeg": 34,
      "idealAltitudeDeg": 50,
      "maxRecommendedMoonIlluminationMain": 55,
      "maxRecommendedMoonIlluminationExtra": 72,
      "minRecommendedMoonDistanceDeg": 50,
      "coreSaturationRisk": "high",
      "framingDifficulty": "moderate",
      "notes": [
        "Very bright high-dynamic-range nebula; core clips easily, faint outer dust still prefers dark sky."
      ]
    }
  },
  {
    "id": "M43",
    "messierNumber": 43,
    "primaryName": "De Mairan's Nebula",
    "aliases": [
      "M43",
      "M 43",
      "43",
      "NGC 1982",
      "De Mairan's Nebula"
    ],
    "raHours": 5.593333,
    "raDeg": 83.899995,
    "decDeg": -5.266667,
    "constellation": "Orion",
    "objectType": "emission_nebula",
    "objectSubType": "Di",
    "visualMagnitude": 9,
    "apparentSizeArcMin": 20,
    "majorAxisArcMin": 20,
    "minorAxisArcMin": 15,
    "distanceLy": "1600",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M44",
    "messierNumber": 44,
    "primaryName": "Beehive Cluster",
    "aliases": [
      "M44",
      "M 44",
      "44",
      "NGC 2632",
      "Beehive Cluster"
    ],
    "raHours": 8.668333,
    "raDeg": 130.024995,
    "decDeg": 19.983333,
    "constellation": "Cancer",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 3.7,
    "apparentSizeArcMin": 95,
    "majorAxisArcMin": 95,
    "minorAxisArcMin": 95,
    "distanceLy": "577",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M45",
    "messierNumber": 45,
    "primaryName": "Pleiades",
    "germanName": "Plejaden",
    "aliases": [
      "M45",
      "M 45",
      "45",
      "Pleiades",
      "Seven Sisters"
    ],
    "raHours": 3.783333,
    "raDeg": 56.749995,
    "decDeg": 24.116667,
    "constellation": "Taurus",
    "objectType": "reflection_nebula",
    "objectSubType": "Oc",
    "visualMagnitude": 1.6,
    "apparentSizeArcMin": 110,
    "majorAxisArcMin": 110,
    "minorAxisArcMin": 110,
    "distanceLy": "380",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92,
    "profileOverrides": {
      "moonSensitivity": 0.94,
      "twilightSensitivity": 0.9,
      "altitudeSensitivity": 0.72,
      "gradientSensitivity": 0.95,
      "faintDetailSensitivity": 0.92,
      "surfaceBrightnessClass": "low",
      "broadbandDifficulty": "hard",
      "minUsableAltitudeDeg": 30,
      "minMainAltitudeDeg": 42,
      "idealAltitudeDeg": 60,
      "maxRecommendedMoonIlluminationMain": 15,
      "maxRecommendedMoonIlluminationExtra": 30,
      "minRecommendedMoonDistanceDeg": 95,
      "coreSaturationRisk": "medium",
      "framingDifficulty": "hard",
      "notes": [
        "Reflection nebulosity is very sensitive to moonlight, haze and gradients."
      ]
    }
  },
  {
    "id": "M46",
    "messierNumber": 46,
    "primaryName": "Messier 46 open cluster",
    "aliases": [
      "M46",
      "M 46",
      "46",
      "NGC 2437"
    ],
    "raHours": 7.696667,
    "raDeg": 115.450005,
    "decDeg": -14.816667,
    "constellation": "Puppis",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 6,
    "apparentSizeArcMin": 27,
    "majorAxisArcMin": 27,
    "minorAxisArcMin": 27,
    "distanceLy": "5400",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M47",
    "messierNumber": 47,
    "primaryName": "Messier 47 open cluster",
    "aliases": [
      "M47",
      "M 47",
      "47",
      "NGC 2422"
    ],
    "raHours": 7.61,
    "raDeg": 114.15,
    "decDeg": -14.5,
    "constellation": "Puppis",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 5.2,
    "apparentSizeArcMin": 30,
    "majorAxisArcMin": 30,
    "minorAxisArcMin": 30,
    "distanceLy": "1600",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M48",
    "messierNumber": 48,
    "primaryName": "Messier 48 open cluster",
    "aliases": [
      "M48",
      "M 48",
      "48",
      "NGC 2548"
    ],
    "raHours": 8.23,
    "raDeg": 123.45,
    "decDeg": -5.8,
    "constellation": "Hydra",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 5.5,
    "apparentSizeArcMin": 54,
    "majorAxisArcMin": 54,
    "minorAxisArcMin": 54,
    "distanceLy": "1500",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M49",
    "messierNumber": 49,
    "primaryName": "Messier 49 elliptical galaxy",
    "aliases": [
      "M49",
      "M 49",
      "49",
      "NGC 4472"
    ],
    "raHours": 12.496667,
    "raDeg": 187.450005,
    "decDeg": 8,
    "constellation": "Virgo",
    "objectType": "galaxy_elliptical",
    "objectSubType": "El",
    "visualMagnitude": 8.4,
    "apparentSizeArcMin": 9,
    "majorAxisArcMin": 9,
    "minorAxisArcMin": 7.5,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M50",
    "messierNumber": 50,
    "primaryName": "Messier 50 open cluster",
    "aliases": [
      "M50",
      "M 50",
      "50",
      "NGC 2323"
    ],
    "raHours": 7.053333,
    "raDeg": 105.799995,
    "decDeg": -8.333333,
    "constellation": "Monoceros",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 6.3,
    "apparentSizeArcMin": 16,
    "majorAxisArcMin": 16,
    "minorAxisArcMin": 16,
    "distanceLy": "3000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M51",
    "messierNumber": 51,
    "primaryName": "Whirlpool Galaxy",
    "germanName": "Whirlpool-Galaxie",
    "aliases": [
      "M51",
      "M 51",
      "51",
      "NGC 5194",
      "Whirlpool Galaxy"
    ],
    "raHours": 13.5,
    "raDeg": 202.5,
    "decDeg": 47.183333,
    "constellation": "Canes Venatici",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 8.4,
    "apparentSizeArcMin": 11,
    "majorAxisArcMin": 11,
    "minorAxisArcMin": 7,
    "distanceLy": "37 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M52",
    "messierNumber": 52,
    "primaryName": "Messier 52 open cluster",
    "aliases": [
      "M52",
      "M 52",
      "52",
      "NGC 7654"
    ],
    "raHours": 23.403333,
    "raDeg": 351.049995,
    "decDeg": 61.583333,
    "constellation": "Cassiopeia",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 7.3,
    "apparentSizeArcMin": 13,
    "majorAxisArcMin": 13,
    "minorAxisArcMin": 13,
    "distanceLy": "5000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M53",
    "messierNumber": 53,
    "primaryName": "Messier 53 globular cluster",
    "aliases": [
      "M53",
      "M 53",
      "53",
      "NGC 5024"
    ],
    "raHours": 13.215,
    "raDeg": 198.225,
    "decDeg": 18.166667,
    "constellation": "Coma Berenices",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 7.6,
    "apparentSizeArcMin": 12.6,
    "majorAxisArcMin": 12.6,
    "minorAxisArcMin": 12.6,
    "distanceLy": "59700",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M54",
    "messierNumber": 54,
    "primaryName": "Messier 54 globular cluster",
    "aliases": [
      "M54",
      "M 54",
      "54",
      "NGC 6715"
    ],
    "raHours": 18.918333,
    "raDeg": 283.774995,
    "decDeg": -30.483333,
    "constellation": "Sagittarius",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 7.6,
    "apparentSizeArcMin": 9.1,
    "majorAxisArcMin": 9.1,
    "minorAxisArcMin": 9.1,
    "distanceLy": "88700",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M55",
    "messierNumber": 55,
    "primaryName": "Messier 55 globular cluster",
    "aliases": [
      "M55",
      "M 55",
      "55",
      "NGC 6809"
    ],
    "raHours": 19.666667,
    "raDeg": 295.000005,
    "decDeg": -30.966667,
    "constellation": "Sagittarius",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 6.3,
    "apparentSizeArcMin": 19,
    "majorAxisArcMin": 19,
    "minorAxisArcMin": 19,
    "distanceLy": "17600",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M56",
    "messierNumber": 56,
    "primaryName": "Messier 56 globular cluster",
    "aliases": [
      "M56",
      "M 56",
      "56",
      "NGC 6779"
    ],
    "raHours": 19.276667,
    "raDeg": 289.150005,
    "decDeg": 30.183333,
    "constellation": "Lyra",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 8.3,
    "apparentSizeArcMin": 7.1,
    "majorAxisArcMin": 7.1,
    "minorAxisArcMin": 7.1,
    "distanceLy": "32900",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M57",
    "messierNumber": 57,
    "primaryName": "Ring Nebula",
    "germanName": "Ringnebel",
    "aliases": [
      "M57",
      "M 57",
      "57",
      "NGC 6720",
      "Ring Nebula"
    ],
    "raHours": 18.893333,
    "raDeg": 283.399995,
    "decDeg": 33.033333,
    "constellation": "Lyra",
    "objectType": "planetary_nebula",
    "objectSubType": "Pl",
    "visualMagnitude": 8.8,
    "apparentSizeArcMin": 1.4,
    "majorAxisArcMin": 1.4,
    "minorAxisArcMin": 1,
    "distanceLy": "2300",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92,
    "profileOverrides": {
      "moonSensitivity": 0.35,
      "twilightSensitivity": 0.4,
      "altitudeSensitivity": 0.72,
      "gradientSensitivity": 0.34,
      "faintDetailSensitivity": 0.42,
      "maxRecommendedMoonIlluminationMain": 70,
      "maxRecommendedMoonIlluminationExtra": 86,
      "notes": [
        "Compact planetary nebula; tolerates moonlight better than faint galaxies."
      ]
    }
  },
  {
    "id": "M58",
    "messierNumber": 58,
    "primaryName": "Messier 58 spiral galaxy",
    "aliases": [
      "M58",
      "M 58",
      "58",
      "NGC 4579"
    ],
    "raHours": 12.628333,
    "raDeg": 189.424995,
    "decDeg": 11.816667,
    "constellation": "Virgo",
    "objectType": "galaxy_spiral",
    "objectSubType": "Ba",
    "visualMagnitude": 9.7,
    "apparentSizeArcMin": 5.5,
    "majorAxisArcMin": 5.5,
    "minorAxisArcMin": 4.5,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M59",
    "messierNumber": 59,
    "primaryName": "Messier 59 elliptical galaxy",
    "aliases": [
      "M59",
      "M 59",
      "59",
      "NGC 4621"
    ],
    "raHours": 12.7,
    "raDeg": 190.5,
    "decDeg": 11.65,
    "constellation": "Virgo",
    "objectType": "galaxy_elliptical",
    "objectSubType": "El",
    "visualMagnitude": 9.6,
    "apparentSizeArcMin": 5,
    "majorAxisArcMin": 5,
    "minorAxisArcMin": 3.5,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M60",
    "messierNumber": 60,
    "primaryName": "Messier 60 elliptical galaxy",
    "aliases": [
      "M60",
      "M 60",
      "60",
      "NGC 4649"
    ],
    "raHours": 12.728333,
    "raDeg": 190.924995,
    "decDeg": 11.55,
    "constellation": "Virgo",
    "objectType": "galaxy_elliptical",
    "objectSubType": "El",
    "visualMagnitude": 8.8,
    "apparentSizeArcMin": 7,
    "majorAxisArcMin": 7,
    "minorAxisArcMin": 6,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M61",
    "messierNumber": 61,
    "primaryName": "Messier 61 spiral galaxy",
    "aliases": [
      "M61",
      "M 61",
      "61",
      "NGC 4303"
    ],
    "raHours": 12.365,
    "raDeg": 185.475,
    "decDeg": 4.466667,
    "constellation": "Virgo",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 9.7,
    "apparentSizeArcMin": 6,
    "majorAxisArcMin": 6,
    "minorAxisArcMin": 5.5,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M62",
    "messierNumber": 62,
    "primaryName": "Messier 62 globular cluster",
    "aliases": [
      "M62",
      "M 62",
      "62",
      "NGC 6266"
    ],
    "raHours": 17.02,
    "raDeg": 255.3,
    "decDeg": -30.116667,
    "constellation": "Ophiuchus",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 6.5,
    "apparentSizeArcMin": 14.1,
    "majorAxisArcMin": 14.1,
    "minorAxisArcMin": 14.1,
    "distanceLy": "22500",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M63",
    "messierNumber": 63,
    "primaryName": "Sunflower Galaxy",
    "germanName": "Sonnenblumengalaxie",
    "aliases": [
      "M63",
      "M 63",
      "63",
      "NGC 5055",
      "Sunflower Galaxy"
    ],
    "raHours": 13.263333,
    "raDeg": 198.949995,
    "decDeg": 42.033333,
    "constellation": "Canes Venatici",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 8.6,
    "apparentSizeArcMin": 10,
    "majorAxisArcMin": 10,
    "minorAxisArcMin": 6,
    "distanceLy": "37 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M64",
    "messierNumber": 64,
    "primaryName": "Black Eye Galaxy",
    "germanName": "Schwarzes Auge Galaxie",
    "aliases": [
      "M64",
      "M 64",
      "64",
      "NGC 4826",
      "Black Eye Galaxy"
    ],
    "raHours": 12.945,
    "raDeg": 194.175,
    "decDeg": 21.683333,
    "constellation": "Coma Berenices",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 8.5,
    "apparentSizeArcMin": 9.3,
    "majorAxisArcMin": 9.3,
    "minorAxisArcMin": 5.4,
    "distanceLy": "19 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M65",
    "messierNumber": 65,
    "primaryName": "Messier 65 spiral galaxy",
    "aliases": [
      "M65",
      "M 65",
      "65",
      "NGC 3623"
    ],
    "raHours": 11.315,
    "raDeg": 169.725,
    "decDeg": 13.083333,
    "constellation": "Leo",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 9.3,
    "apparentSizeArcMin": 8,
    "majorAxisArcMin": 8,
    "minorAxisArcMin": 1.5,
    "distanceLy": "35 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M66",
    "messierNumber": 66,
    "primaryName": "Messier 66 spiral galaxy",
    "aliases": [
      "M66",
      "M 66",
      "66",
      "NGC 3627"
    ],
    "raHours": 11.336667,
    "raDeg": 170.050005,
    "decDeg": 12.983333,
    "constellation": "Leo",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 8.9,
    "apparentSizeArcMin": 8,
    "majorAxisArcMin": 8,
    "minorAxisArcMin": 2.5,
    "distanceLy": "35 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M67",
    "messierNumber": 67,
    "primaryName": "Messier 67 open cluster",
    "aliases": [
      "M67",
      "M 67",
      "67",
      "NGC 2682"
    ],
    "raHours": 8.84,
    "raDeg": 132.6,
    "decDeg": 11.816667,
    "constellation": "Cancer",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 6.1,
    "apparentSizeArcMin": 30,
    "majorAxisArcMin": 30,
    "minorAxisArcMin": 30,
    "distanceLy": "2700",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M68",
    "messierNumber": 68,
    "primaryName": "Messier 68 globular cluster",
    "aliases": [
      "M68",
      "M 68",
      "68",
      "NGC 4590"
    ],
    "raHours": 12.658333,
    "raDeg": 189.874995,
    "decDeg": -26.75,
    "constellation": "Hydra",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 7.8,
    "apparentSizeArcMin": 12,
    "majorAxisArcMin": 12,
    "minorAxisArcMin": 12,
    "distanceLy": "33300",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M69",
    "messierNumber": 69,
    "primaryName": "Messier 69 globular cluster",
    "aliases": [
      "M69",
      "M 69",
      "69",
      "NGC 6637"
    ],
    "raHours": 18.523333,
    "raDeg": 277.849995,
    "decDeg": -32.35,
    "constellation": "Sagittarius",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 7.6,
    "apparentSizeArcMin": 7.1,
    "majorAxisArcMin": 7.1,
    "minorAxisArcMin": 7.1,
    "distanceLy": "28000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M70",
    "messierNumber": 70,
    "primaryName": "Messier 70 globular cluster",
    "aliases": [
      "M70",
      "M 70",
      "70",
      "NGC 6681"
    ],
    "raHours": 18.72,
    "raDeg": 280.8,
    "decDeg": -32.3,
    "constellation": "Sagittarius",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 7.9,
    "apparentSizeArcMin": 7.8,
    "majorAxisArcMin": 7.8,
    "minorAxisArcMin": 7.8,
    "distanceLy": "29400",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M71",
    "messierNumber": 71,
    "primaryName": "Messier 71 globular cluster",
    "aliases": [
      "M71",
      "M 71",
      "71",
      "NGC 6838"
    ],
    "raHours": 19.896667,
    "raDeg": 298.450005,
    "decDeg": 18.783333,
    "constellation": "Sagitta",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 8.2,
    "apparentSizeArcMin": 7.2,
    "majorAxisArcMin": 7.2,
    "minorAxisArcMin": 7.2,
    "distanceLy": "12700",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M72",
    "messierNumber": 72,
    "primaryName": "Messier 72 globular cluster",
    "aliases": [
      "M72",
      "M 72",
      "72",
      "NGC 6981"
    ],
    "raHours": 20.891667,
    "raDeg": 313.375005,
    "decDeg": -12.533333,
    "constellation": "Aquarius",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 9.3,
    "apparentSizeArcMin": 5.9,
    "majorAxisArcMin": 5.9,
    "minorAxisArcMin": 5.9,
    "distanceLy": "55400",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M73",
    "messierNumber": 73,
    "primaryName": "Messier 73 asterism",
    "aliases": [
      "M73",
      "M 73",
      "73",
      "NGC 6994"
    ],
    "raHours": 20.983333,
    "raDeg": 314.749995,
    "decDeg": -12.633333,
    "constellation": "Aquarius",
    "objectType": "asterism",
    "objectSubType": "As",
    "visualMagnitude": 9,
    "apparentSizeArcMin": 2.8,
    "majorAxisArcMin": 2.8,
    "minorAxisArcMin": 2.8,
    "distanceLy": "2000",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M74",
    "messierNumber": 74,
    "primaryName": "Messier 74 spiral galaxy",
    "aliases": [
      "M74",
      "M 74",
      "74",
      "NGC 628"
    ],
    "raHours": 1.611667,
    "raDeg": 24.175005,
    "decDeg": 15.783333,
    "constellation": "Pisces",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 9.4,
    "apparentSizeArcMin": 10.2,
    "majorAxisArcMin": 10.2,
    "minorAxisArcMin": 9.5,
    "distanceLy": "35 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92,
    "profileOverrides": {
      "moonSensitivity": 0.96,
      "twilightSensitivity": 0.95,
      "altitudeSensitivity": 0.9,
      "gradientSensitivity": 0.96,
      "faintDetailSensitivity": 1,
      "surfaceBrightnessClass": "very_low",
      "broadbandDifficulty": "extreme",
      "minMainAltitudeDeg": 46,
      "maxRecommendedMoonIlluminationMain": 12,
      "maxRecommendedMoonIlluminationExtra": 28,
      "minRecommendedMoonDistanceDeg": 100,
      "notes": [
        "Low-surface-brightness face-on galaxy; score is intentionally strict."
      ]
    }
  },
  {
    "id": "M75",
    "messierNumber": 75,
    "primaryName": "Messier 75 globular cluster",
    "aliases": [
      "M75",
      "M 75",
      "75",
      "NGC 6864"
    ],
    "raHours": 20.101667,
    "raDeg": 301.525005,
    "decDeg": -21.916667,
    "constellation": "Sagittarius",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 8.5,
    "apparentSizeArcMin": 6,
    "majorAxisArcMin": 6,
    "minorAxisArcMin": 6,
    "distanceLy": "61300",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M76",
    "messierNumber": 76,
    "primaryName": "Little Dumbbell Nebula",
    "aliases": [
      "M76",
      "M 76",
      "76",
      "NGC 650",
      "Little Dumbbell Nebula"
    ],
    "raHours": 1.706667,
    "raDeg": 25.600005,
    "decDeg": 51.566667,
    "constellation": "Perseus",
    "objectType": "planetary_nebula",
    "objectSubType": "Pl",
    "visualMagnitude": 10.1,
    "apparentSizeArcMin": 2.7,
    "majorAxisArcMin": 2.7,
    "minorAxisArcMin": 1.8,
    "distanceLy": "3400",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M77",
    "messierNumber": 77,
    "primaryName": "Messier 77 spiral galaxy",
    "aliases": [
      "M77",
      "M 77",
      "77",
      "NGC 1068"
    ],
    "raHours": 2.711667,
    "raDeg": 40.675005,
    "decDeg": 0.033333,
    "constellation": "Cetus",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 8.9,
    "apparentSizeArcMin": 7,
    "majorAxisArcMin": 7,
    "minorAxisArcMin": 6,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M78",
    "messierNumber": 78,
    "primaryName": "Messier 78 reflection nebula",
    "aliases": [
      "M78",
      "M 78",
      "78",
      "NGC 2068"
    ],
    "raHours": 5.778333,
    "raDeg": 86.674995,
    "decDeg": 0.05,
    "constellation": "Orion",
    "objectType": "reflection_nebula",
    "objectSubType": "Di",
    "visualMagnitude": 8.3,
    "apparentSizeArcMin": 8,
    "majorAxisArcMin": 8,
    "minorAxisArcMin": 6,
    "distanceLy": "1600",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M79",
    "messierNumber": 79,
    "primaryName": "Messier 79 globular cluster",
    "aliases": [
      "M79",
      "M 79",
      "79",
      "NGC 1904"
    ],
    "raHours": 5.408333,
    "raDeg": 81.124995,
    "decDeg": -24.55,
    "constellation": "Lepus",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 7.7,
    "apparentSizeArcMin": 8.7,
    "majorAxisArcMin": 8.7,
    "minorAxisArcMin": 8.7,
    "distanceLy": "42100",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M80",
    "messierNumber": 80,
    "primaryName": "Messier 80 globular cluster",
    "aliases": [
      "M80",
      "M 80",
      "80",
      "NGC 6093"
    ],
    "raHours": 16.283333,
    "raDeg": 244.249995,
    "decDeg": -22.983333,
    "constellation": "Scorpius",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 7.3,
    "apparentSizeArcMin": 8.9,
    "majorAxisArcMin": 8.9,
    "minorAxisArcMin": 8.9,
    "distanceLy": "32600",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M81",
    "messierNumber": 81,
    "primaryName": "Bode's Galaxy",
    "germanName": "Bodes Galaxie",
    "aliases": [
      "M81",
      "M 81",
      "81",
      "NGC 3031",
      "Bode's Galaxy",
      "Bodes Galaxy"
    ],
    "raHours": 9.926667,
    "raDeg": 148.900005,
    "decDeg": 69.066667,
    "constellation": "Ursa Major",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 6.9,
    "apparentSizeArcMin": 21,
    "majorAxisArcMin": 21,
    "minorAxisArcMin": 10,
    "distanceLy": "12 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92,
    "profileOverrides": {
      "moonSensitivity": 0.82,
      "twilightSensitivity": 0.82,
      "altitudeSensitivity": 0.78,
      "gradientSensitivity": 0.82,
      "faintDetailSensitivity": 0.84,
      "surfaceBrightnessClass": "low",
      "broadbandDifficulty": "hard",
      "minUsableAltitudeDeg": 30,
      "minMainAltitudeDeg": 40,
      "idealAltitudeDeg": 60,
      "maxRecommendedMoonIlluminationMain": 28,
      "maxRecommendedMoonIlluminationExtra": 48,
      "minRecommendedMoonDistanceDeg": 78,
      "notes": [
        "Smaller than M31; outer arms and halo are more dependent on dark sky."
      ]
    }
  },
  {
    "id": "M82",
    "messierNumber": 82,
    "primaryName": "Cigar Galaxy",
    "germanName": "Zigarrengalaxie",
    "aliases": [
      "M82",
      "M 82",
      "82",
      "NGC 3034",
      "Cigar Galaxy"
    ],
    "raHours": 9.93,
    "raDeg": 148.95,
    "decDeg": 69.683333,
    "constellation": "Ursa Major",
    "objectType": "galaxy_irregular",
    "objectSubType": "Ir",
    "visualMagnitude": 8.4,
    "apparentSizeArcMin": 9,
    "majorAxisArcMin": 9,
    "minorAxisArcMin": 4,
    "distanceLy": "12 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92,
    "profileOverrides": {
      "moonSensitivity": 0.7,
      "twilightSensitivity": 0.74,
      "altitudeSensitivity": 0.76,
      "gradientSensitivity": 0.7,
      "faintDetailSensitivity": 0.68,
      "surfaceBrightnessClass": "medium",
      "broadbandDifficulty": "moderate",
      "minUsableAltitudeDeg": 28,
      "minMainAltitudeDeg": 38,
      "idealAltitudeDeg": 58,
      "maxRecommendedMoonIlluminationMain": 42,
      "maxRecommendedMoonIlluminationExtra": 60,
      "minRecommendedMoonDistanceDeg": 65,
      "notes": [
        "Relatively bright and contrasty, but still a broadband galaxy target."
      ]
    }
  },
  {
    "id": "M83",
    "messierNumber": 83,
    "primaryName": "Southern Pinwheel",
    "aliases": [
      "M83",
      "M 83",
      "83",
      "NGC 5236",
      "Southern Pinwheel"
    ],
    "raHours": 13.616667,
    "raDeg": 204.250005,
    "decDeg": -29.866667,
    "constellation": "Hydra",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 7.6,
    "apparentSizeArcMin": 11,
    "majorAxisArcMin": 11,
    "minorAxisArcMin": 10,
    "distanceLy": "15 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M84",
    "messierNumber": 84,
    "primaryName": "Messier 84 spiral galaxy",
    "aliases": [
      "M84",
      "M 84",
      "84",
      "NGC 4374"
    ],
    "raHours": 12.418333,
    "raDeg": 186.274995,
    "decDeg": 12.883333,
    "constellation": "Virgo",
    "objectType": "galaxy_spiral",
    "objectSubType": "Ln",
    "visualMagnitude": 9.1,
    "apparentSizeArcMin": 5,
    "majorAxisArcMin": 5,
    "minorAxisArcMin": 5,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M85",
    "messierNumber": 85,
    "primaryName": "Messier 85 spiral galaxy",
    "aliases": [
      "M85",
      "M 85",
      "85",
      "NGC 4382"
    ],
    "raHours": 12.425,
    "raDeg": 186.375,
    "decDeg": 18.2,
    "constellation": "Coma Berenices",
    "objectType": "galaxy_spiral",
    "objectSubType": "Ln",
    "visualMagnitude": 9.1,
    "apparentSizeArcMin": 7.1,
    "majorAxisArcMin": 7.1,
    "minorAxisArcMin": 5.2,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M86",
    "messierNumber": 86,
    "primaryName": "Messier 86 spiral galaxy",
    "aliases": [
      "M86",
      "M 86",
      "86",
      "NGC 4406"
    ],
    "raHours": 12.436667,
    "raDeg": 186.550005,
    "decDeg": 12.95,
    "constellation": "Virgo",
    "objectType": "galaxy_spiral",
    "objectSubType": "Ln",
    "visualMagnitude": 8.9,
    "apparentSizeArcMin": 7.5,
    "majorAxisArcMin": 7.5,
    "minorAxisArcMin": 5.5,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M87",
    "messierNumber": 87,
    "primaryName": "Messier 87 elliptical galaxy",
    "aliases": [
      "M87",
      "M 87",
      "87",
      "NGC 4486"
    ],
    "raHours": 12.513333,
    "raDeg": 187.699995,
    "decDeg": 12.4,
    "constellation": "Virgo",
    "objectType": "galaxy_elliptical",
    "objectSubType": "El",
    "visualMagnitude": 8.6,
    "apparentSizeArcMin": 7,
    "majorAxisArcMin": 7,
    "minorAxisArcMin": 7,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M88",
    "messierNumber": 88,
    "primaryName": "Messier 88 spiral galaxy",
    "aliases": [
      "M88",
      "M 88",
      "88",
      "NGC 4501"
    ],
    "raHours": 12.535,
    "raDeg": 188.025,
    "decDeg": 14.433333,
    "constellation": "Coma Berenices",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 9.6,
    "apparentSizeArcMin": 7,
    "majorAxisArcMin": 7,
    "minorAxisArcMin": 4,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M89",
    "messierNumber": 89,
    "primaryName": "Messier 89 elliptical galaxy",
    "aliases": [
      "M89",
      "M 89",
      "89",
      "NGC 4552"
    ],
    "raHours": 12.595,
    "raDeg": 188.925,
    "decDeg": 12.55,
    "constellation": "Virgo",
    "objectType": "galaxy_elliptical",
    "objectSubType": "El",
    "visualMagnitude": 9.8,
    "apparentSizeArcMin": 4,
    "majorAxisArcMin": 4,
    "minorAxisArcMin": 4,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M90",
    "messierNumber": 90,
    "primaryName": "Messier 90 spiral galaxy",
    "aliases": [
      "M90",
      "M 90",
      "90",
      "NGC 4569"
    ],
    "raHours": 12.613333,
    "raDeg": 189.199995,
    "decDeg": 13.166667,
    "constellation": "Virgo",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 9.5,
    "apparentSizeArcMin": 9.5,
    "majorAxisArcMin": 9.5,
    "minorAxisArcMin": 4.5,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M91",
    "messierNumber": 91,
    "primaryName": "Messier 91 spiral galaxy",
    "aliases": [
      "M91",
      "M 91",
      "91",
      "NGC 4548"
    ],
    "raHours": 12.591667,
    "raDeg": 188.875005,
    "decDeg": 14.5,
    "constellation": "Coma Berenices",
    "objectType": "galaxy_spiral",
    "objectSubType": "Ba",
    "visualMagnitude": 10.2,
    "apparentSizeArcMin": 5.4,
    "majorAxisArcMin": 5.4,
    "minorAxisArcMin": 4.4,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M92",
    "messierNumber": 92,
    "primaryName": "Messier 92 globular cluster",
    "aliases": [
      "M92",
      "M 92",
      "92",
      "NGC 6341"
    ],
    "raHours": 17.285,
    "raDeg": 259.275,
    "decDeg": 43.133333,
    "constellation": "Hercules",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 6.4,
    "apparentSizeArcMin": 11.2,
    "majorAxisArcMin": 11.2,
    "minorAxisArcMin": 11.2,
    "distanceLy": "26700",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M93",
    "messierNumber": 93,
    "primaryName": "Messier 93 open cluster",
    "aliases": [
      "M93",
      "M 93",
      "93",
      "NGC 2447"
    ],
    "raHours": 7.743333,
    "raDeg": 116.149995,
    "decDeg": -23.866667,
    "constellation": "Puppis",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 6,
    "apparentSizeArcMin": 22,
    "majorAxisArcMin": 22,
    "minorAxisArcMin": 22,
    "distanceLy": "3600",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M94",
    "messierNumber": 94,
    "primaryName": "Messier 94 spiral galaxy",
    "aliases": [
      "M94",
      "M 94",
      "94",
      "NGC 4736"
    ],
    "raHours": 12.848333,
    "raDeg": 192.724995,
    "decDeg": 41.133333,
    "constellation": "Canes Venatici",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 8.2,
    "apparentSizeArcMin": 7,
    "majorAxisArcMin": 7,
    "minorAxisArcMin": 3,
    "distanceLy": "15 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M95",
    "messierNumber": 95,
    "primaryName": "Messier 95 spiral galaxy",
    "aliases": [
      "M95",
      "M 95",
      "95",
      "NGC 3351"
    ],
    "raHours": 10.733333,
    "raDeg": 160.999995,
    "decDeg": 11.7,
    "constellation": "Leo",
    "objectType": "galaxy_spiral",
    "objectSubType": "Ba",
    "visualMagnitude": 9.7,
    "apparentSizeArcMin": 4.4,
    "majorAxisArcMin": 4.4,
    "minorAxisArcMin": 3.3,
    "distanceLy": "38 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M96",
    "messierNumber": 96,
    "primaryName": "Messier 96 spiral galaxy",
    "aliases": [
      "M96",
      "M 96",
      "96",
      "NGC 3368"
    ],
    "raHours": 10.78,
    "raDeg": 161.7,
    "decDeg": 11.816667,
    "constellation": "Leo",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 9.2,
    "apparentSizeArcMin": 6,
    "majorAxisArcMin": 6,
    "minorAxisArcMin": 4,
    "distanceLy": "38 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M97",
    "messierNumber": 97,
    "primaryName": "Owl Nebula",
    "germanName": "Eulennebel",
    "aliases": [
      "M97",
      "M 97",
      "97",
      "NGC 3587",
      "Owl Nebula"
    ],
    "raHours": 11.246667,
    "raDeg": 168.700005,
    "decDeg": 55.016667,
    "constellation": "Ursa Major",
    "objectType": "planetary_nebula",
    "objectSubType": "Pl",
    "visualMagnitude": 9.9,
    "apparentSizeArcMin": 3.4,
    "majorAxisArcMin": 3.4,
    "minorAxisArcMin": 3.3,
    "distanceLy": "2600",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M98",
    "messierNumber": 98,
    "primaryName": "Messier 98 spiral galaxy",
    "aliases": [
      "M98",
      "M 98",
      "98",
      "NGC 4192"
    ],
    "raHours": 12.231667,
    "raDeg": 183.475005,
    "decDeg": 14.916667,
    "constellation": "Coma Berenices",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 10.1,
    "apparentSizeArcMin": 9.5,
    "majorAxisArcMin": 9.5,
    "minorAxisArcMin": 3.2,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M99",
    "messierNumber": 99,
    "primaryName": "Messier 99 spiral galaxy",
    "aliases": [
      "M99",
      "M 99",
      "99",
      "NGC 4254"
    ],
    "raHours": 12.315,
    "raDeg": 184.725,
    "decDeg": 14.433333,
    "constellation": "Coma Berenices",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 9.9,
    "apparentSizeArcMin": 5.4,
    "majorAxisArcMin": 5.4,
    "minorAxisArcMin": 4.8,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M100",
    "messierNumber": 100,
    "primaryName": "Messier 100 spiral galaxy",
    "aliases": [
      "M100",
      "M 100",
      "100",
      "NGC 4321"
    ],
    "raHours": 12.383333,
    "raDeg": 185.749995,
    "decDeg": 15.833333,
    "constellation": "Coma Berenices",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 9.3,
    "apparentSizeArcMin": 7,
    "majorAxisArcMin": 7,
    "minorAxisArcMin": 6,
    "distanceLy": "60 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M101",
    "messierNumber": 101,
    "primaryName": "Pinwheel Galaxy",
    "germanName": "Feuerradgalaxie",
    "aliases": [
      "M101",
      "M 101",
      "101",
      "NGC 5457",
      "Pinwheel Galaxy"
    ],
    "raHours": 14.053333,
    "raDeg": 210.799995,
    "decDeg": 54.35,
    "constellation": "Ursa Major",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 7.9,
    "apparentSizeArcMin": 22,
    "majorAxisArcMin": 22,
    "minorAxisArcMin": 22,
    "distanceLy": "27 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92,
    "profileOverrides": {
      "moonSensitivity": 0.98,
      "twilightSensitivity": 0.97,
      "altitudeSensitivity": 0.92,
      "gradientSensitivity": 0.98,
      "faintDetailSensitivity": 1,
      "surfaceBrightnessClass": "very_low",
      "broadbandDifficulty": "extreme",
      "minUsableAltitudeDeg": 35,
      "minMainAltitudeDeg": 48,
      "idealAltitudeDeg": 65,
      "maxRecommendedMoonIlluminationMain": 10,
      "maxRecommendedMoonIlluminationExtra": 25,
      "minRecommendedMoonDistanceDeg": 105,
      "notes": [
        "Weak face-on galaxy; moonlight, twilight and low altitude are heavily penalized."
      ]
    }
  },
  {
    "id": "M102",
    "messierNumber": 102,
    "primaryName": "Spindle Galaxy",
    "aliases": [
      "M102",
      "M 102",
      "102",
      "NGC 5866",
      "Spindle Galaxy"
    ],
    "raHours": 15.108333,
    "raDeg": 226.624995,
    "decDeg": 55.766667,
    "constellation": "Draco",
    "objectType": "galaxy_spiral",
    "objectSubType": "Ln",
    "visualMagnitude": 9.9,
    "apparentSizeArcMin": 5.2,
    "majorAxisArcMin": 5.2,
    "minorAxisArcMin": 2.3,
    "distanceLy": "40 million",
    "notes": [
      "Historically ambiguous / spurious Messier object; commonly associated with NGC 5866."
    ],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M103",
    "messierNumber": 103,
    "primaryName": "Messier 103 open cluster",
    "aliases": [
      "M103",
      "M 103",
      "103",
      "NGC 581"
    ],
    "raHours": 1.553333,
    "raDeg": 23.299995,
    "decDeg": 60.7,
    "constellation": "Cassiopeia",
    "objectType": "open_cluster",
    "objectSubType": "Oc",
    "visualMagnitude": 7.4,
    "apparentSizeArcMin": 6,
    "majorAxisArcMin": 6,
    "minorAxisArcMin": 6,
    "distanceLy": "8500",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M104",
    "messierNumber": 104,
    "primaryName": "Sombrero Galaxy",
    "germanName": "Sombrerogalaxie",
    "aliases": [
      "M104",
      "M 104",
      "104",
      "NGC 4594",
      "Sombrero Galaxy"
    ],
    "raHours": 12.666667,
    "raDeg": 190.000005,
    "decDeg": -11.616667,
    "constellation": "Virgo",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 8,
    "apparentSizeArcMin": 9,
    "majorAxisArcMin": 9,
    "minorAxisArcMin": 4,
    "distanceLy": "50 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M105",
    "messierNumber": 105,
    "primaryName": "Messier 105 elliptical galaxy",
    "aliases": [
      "M105",
      "M 105",
      "105",
      "NGC 3379"
    ],
    "raHours": 10.796667,
    "raDeg": 161.950005,
    "decDeg": 12.583333,
    "constellation": "Leo",
    "objectType": "galaxy_elliptical",
    "objectSubType": "El",
    "visualMagnitude": 9.3,
    "apparentSizeArcMin": 2,
    "majorAxisArcMin": 2,
    "minorAxisArcMin": 2,
    "distanceLy": "38 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M106",
    "messierNumber": 106,
    "primaryName": "Messier 106 spiral galaxy",
    "aliases": [
      "M106",
      "M 106",
      "106",
      "NGC 4258"
    ],
    "raHours": 12.315,
    "raDeg": 184.725,
    "decDeg": 47.316667,
    "constellation": "Canes Venatici",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 8.4,
    "apparentSizeArcMin": 19,
    "majorAxisArcMin": 19,
    "minorAxisArcMin": 8,
    "distanceLy": "25 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M107",
    "messierNumber": 107,
    "primaryName": "Messier 107 globular cluster",
    "aliases": [
      "M107",
      "M 107",
      "107",
      "NGC 6171"
    ],
    "raHours": 16.541667,
    "raDeg": 248.125005,
    "decDeg": -13.05,
    "constellation": "Ophiuchus",
    "objectType": "globular_cluster",
    "objectSubType": "Gc",
    "visualMagnitude": 7.9,
    "apparentSizeArcMin": 10,
    "majorAxisArcMin": 10,
    "minorAxisArcMin": 10,
    "distanceLy": "20900",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M108",
    "messierNumber": 108,
    "primaryName": "Messier 108 spiral galaxy",
    "aliases": [
      "M108",
      "M 108",
      "108",
      "NGC 3556"
    ],
    "raHours": 11.191667,
    "raDeg": 167.875005,
    "decDeg": 55.666667,
    "constellation": "Ursa Major",
    "objectType": "galaxy_spiral",
    "objectSubType": "Sp",
    "visualMagnitude": 10,
    "apparentSizeArcMin": 8,
    "majorAxisArcMin": 8,
    "minorAxisArcMin": 1,
    "distanceLy": "45 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M109",
    "messierNumber": 109,
    "primaryName": "Messier 109 spiral galaxy",
    "aliases": [
      "M109",
      "M 109",
      "109",
      "NGC 3992"
    ],
    "raHours": 11.96,
    "raDeg": 179.4,
    "decDeg": 53.383333,
    "constellation": "Ursa Major",
    "objectType": "galaxy_spiral",
    "objectSubType": "Ba",
    "visualMagnitude": 9.8,
    "apparentSizeArcMin": 7,
    "majorAxisArcMin": 7,
    "minorAxisArcMin": 4,
    "distanceLy": "55 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  },
  {
    "id": "M110",
    "messierNumber": 110,
    "primaryName": "Messier 110 elliptical galaxy",
    "aliases": [
      "M110",
      "M 110",
      "110",
      "NGC 205"
    ],
    "raHours": 0.673333,
    "raDeg": 10.099995,
    "decDeg": 41.683333,
    "constellation": "Andromeda",
    "objectType": "galaxy_elliptical",
    "objectSubType": "El",
    "visualMagnitude": 8.5,
    "apparentSizeArcMin": 17,
    "majorAxisArcMin": 17,
    "minorAxisArcMin": 10,
    "distanceLy": "3 million",
    "notes": [],
    "dataQuality": "complete",
    "dataCompleteness": 0.92
  }
];

export const messierCatalog: DeepSkyObject[] = messierCatalogSeeds.map((seed) => {
  const { profileOverrides, ...object } = seed;
  return {
    ...object,
    planningProfile: buildPlanningProfile(object.objectType, object, profileOverrides)
  };
});

export function getMessierObject(id: string): DeepSkyObject | null {
  const normalized = id.trim().toUpperCase().replace(/^M\s+/, "M");
  return messierCatalog.find((object) => object.id === normalized) ?? null;
}
